package:
    name: durolib
    version: 1.1.0

source:
    git_rev: 1.1.0
    git_url: git://github.com/durack1/durolib.git

build:
  number: 1
  noarch: True
#  noarch_python: True

requirements:
  build:
    - python >=2.7.14,<3
    - setuptools >=39.2.0
  run:
    - python >=2.7.14,<3
    - cdms2 >=3.0
    - cdutil >=8.0
    - pytz >=2018.4
    - scipy >=1.1.0
    - seawater >=3.3.4
about:
    home:  http://github.com/durack1/durolib