package:
    name: durolib
    version: 1.0.2

source:
    git_rev: 1.0.2
    git_url: git://github.com/durack1/durolib.git

build:
  number: 0
  noarch: True
#  noarch_python: True

requirements:
  build:
    - python >=2.7.13,<3
    - setuptools
  run:
    - python >=2.7.13,<3
    - cdms2 >=2.8
    - cdutil
    - pytz
    - seawater
about:
    home:  http://github.com/durack1/durolib
