package:
    name: durolib
    version: 1.1.2

source:
    git_rev: 1.1.2
    git_url: git://github.com/durack1/durolib.git

build:
  number: 4
  noarch: True
#  noarch_python: True

requirements:
  build:
    - python >=2.7.15,<3
    - setuptools >=40.8
  run:
    - python >=2.7.15,<3
    - cdms2 >=3.1.2
    - cdutil >=8.1
    - numpy >=1.16.2
    - pytz >=2018.9
    - scipy >=1.2.1
    - seawater >=3.3.4
about:
    home:  http://github.com/durack1/durolib